version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ashokit_ecomm
      MYSQL_USER: admin
      MYSQL_PASSWORD: ashokit123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: products_api
    restart: always
    depends_on:
      - mysql
    ports:
      - "7777:7777"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ashokit_ecomm
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: ashokit123
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
